src/ru/netcracker/studportal/beans/Professor.java
package ru.netcracker.studportal.beans;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;

@ManagedBean
@SessionScoped
public class Professor {
    private Long id;
    private String surname;
    private String name;
    private String middleName;
    private ArrayList<Subject> subjectList = new ArrayList<Subject>();


    public ArrayList<Subject> getSubjectList() {
        return subjectList;
    }

    public String getAllSubjectsAsString() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < subjectList.size(); i++) {
            Subject sub = subjectList.get(i);
            if (i==0)sb.append(sub.getSubjectName());
            else sb.append(", ").append(sub.getSubjectName());
        }
        return sb.toString();
    }

    public void setSubjectList(ArrayList<Subject> subjectList) {
        this.subjectList = subjectList;
    }
    public void addSubject(Subject sub){
        subjectList.add(sub);
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
}

src/ru/netcracker/studportal/beans/Student.java
package ru.netcracker.studportal.beans;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;

@ManagedBean
@SessionScoped
public class Student implements Serializable{

    private Long id;
    private String surname;
    private String name;
    private String middleName;
    private String groupNumber;
    private String groupSpecialty;

    public Student() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getGroupNumber() {
        return groupNumber;
    }

    public void setGroupNumber(String groupNumber) {
        this.groupNumber = groupNumber;
    }

    public String getGroupSpecialty() {
        return groupSpecialty;
    }

    public void setGroupSpecialty(String groupSpecialty) {
        this.groupSpecialty = groupSpecialty;
    }
}

src/ru/netcracker/studportal/entity/Professor.java
package ru.netcracker.studportal.entity;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Created by user on 11.09.2016.
 */
@Entity
@Table(name = "professors", schema = "", catalog = "studentdb")
public class Professor {
    private long professorId;
    private String surname;
    private String name;
    private String middlename;
    private Set<Subject> profSubjectSet = new HashSet<Subject>();

    @Id
    @Column(name = "professorId")
    public long getProfessorId() {
        return professorId;
    }

    public void setProfessorId(long professorId) {
        this.professorId = professorId;
    }

    @Basic
    @Column(name = "surname")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "middlename")
    public String getMiddlename() {
        return middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Professor that = (Professor) o;

        if (professorId != that.professorId) return false;
        if (middlename != null ? !middlename.equals(that.middlename) : that.middlename != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (surname != null ? !surname.equals(that.surname) : that.surname != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (int) (professorId ^ (professorId >>> 32));
        result = 31 * result + (surname != null ? surname.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (middlename != null ? middlename.hashCode() : 0);
        return result;
    }
    @ManyToMany
    @JoinTable(name = "profsub", catalog = "studentdb", schema = "", joinColumns = @JoinColumn(name = "professorID", referencedColumnName = "professorId", nullable = false), inverseJoinColumns = @JoinColumn(name = "subjectID", referencedColumnName = "subjectID", nullable = false))
    public Set<Subject> getProfSubjectSet() {
        return profSubjectSet;
    }
    public void setProfSubjectSet(Set<Subject> profSubjectSet) {
        this.profSubjectSet = profSubjectSet;
    }
}

src/ru/netcracker/studportal/entity/Student.java
package ru.netcracker.studportal.entity;


import javax.persistence.*;

@Entity
@Table(name = "students", schema = "", catalog = "studentdb")
public class Student {
    private long studentId;
    private String surname;
    private String name;
    private String middlename;
    private Group studentGroup;

    @Id
    @Column(name = "studentId")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getStudentId() {
        return studentId;
    }

    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }

    @Basic
    @Column(name = "surname")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "middlename")
    public String getMiddlename() {
        return middlename;
    }

    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Student that = (Student) o;

        if (studentId != that.studentId) return false;
        if (middlename != null ? !middlename.equals(that.middlename) : that.middlename != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (surname != null ? !surname.equals(that.surname) : that.surname != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (int) (studentId ^ (studentId >>> 32));
        result = 31 * result + (surname != null ? surname.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (middlename != null ? middlename.hashCode() : 0);
        return result;
    }
    @ManyToOne
    @JoinColumn(name = "groupID", referencedColumnName = "groupId", nullable = false)
    public Group getStudentGroup() {
        return studentGroup;
    }

    public void setStudentGroup(Group studentGroup) {
        this.studentGroup = studentGroup;
    }

}

src/ru/netcracker/studportal/controllers/FacultyController.java
package ru.netcracker.studportal.controllers;

import ru.netcracker.studportal.db.DataHelper;
import ru.netcracker.studportal.entity.Faculty;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.List;

@ManagedBean(eager = true)
@SessionScoped
public class FacultyController {
    private List<Faculty> facultyList;

    public FacultyController() {
        facultyList = getAllFaculties();
    }

    public List<Faculty> getAllFaculties(){
        return DataHelper.getInstance().getAllFaculties();
    }

    public List<Faculty> getFacultyList() {
        return facultyList;
    }
}

src/ru/netcracker/studportal/controllers/ProfessorController.java
package ru.netcracker.studportal.controllers;

import ru.netcracker.studportal.beans.Professor;
import ru.netcracker.studportal.beans.Subject;
import ru.netcracker.studportal.db.Database;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

@ManagedBean(eager = true)
@SessionScoped
public class ProfessorController implements Serializable{
    private ArrayList<Professor> professorList;
    public ProfessorController() {
        professorList = new ArrayList<Professor>();
        getAllProfessor();
        getProfessorsSubjects();
    }
    public void getAllProfessor(){
        String sql = "select * from professors";
        getProfessorBySQL(sql);
    }
    private void getProfessorBySQL(String sql){
        Statement stmt = null;
        ResultSet rs = null;
        Connection connection = null;
        try{
            connection = Database.getConnection();
            stmt = connection.createStatement();
            rs = stmt.executeQuery(sql);
            while (rs.next()){
                Professor prof = new Professor();
                prof.setId(rs.getLong("professorId"));
                prof.setSurname(rs.getString("surname"));
                prof.setName(rs.getString("name"));
                prof.setMiddleName(rs.getString("middlename"));
                professorList.add(prof);
            }
        } catch (SQLException e) {
                Logger.getLogger(ProfessorController.class.getName()).log(Level.SEVERE, null, e);
        }finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (rs != null) {
                    rs.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                Logger.getLogger(ProfessorController.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }
    public void getProfessorsSubjects(){
        for (Professor professor : professorList) {
            Statement stmt = null;
            ResultSet rs = null;
            Connection connection = null;
            try{
                connection = Database.getConnection();
                stmt = connection.createStatement();
                rs = stmt.executeQuery("SELECT * FROM profsub as ps " +
                        "inner join subjects sub " +
                        "where ps.professorID="+professor.getId()+" and ps.subjectID=sub.subjectID;");
                while (rs.next()){
                    Subject sub = new Subject();
                    sub.setId(rs.getLong("subjectID"));
                    sub.setSubjectName(rs.getString("subjectName"));
                    professor.addSubject(sub);
                }
            } catch (SQLException e) {
                Logger.getLogger(ProfessorController.class.getName()).log(Level.SEVERE, null, e);
            }finally {
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                    if (rs != null) {
                        rs.close();
                    }
                    if (connection != null) {
                        connection.close();
                    }
                } catch (SQLException e) {
                    Logger.getLogger(ProfessorController.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }
    }
    public void updateData(){
        professorList.clear();
        getAllProfessor();
        getProfessorsSubjects();
    }

    public ArrayList<Professor> getProfessorList() {
        return professorList;
    }
}

src/ru/netcracker/studportal/controllers/StudentController.java
package ru.netcracker.studportal.controllers;

import ru.netcracker.studportal.db.DataHelper;
import ru.netcracker.studportal.entity.Student;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.List;

@ManagedBean(eager = true)
@SessionScoped
public class StudentController implements Serializable{
    private List<Student> studentList;
    public StudentController() {
        getAllStudent();
    }
    public void saveOrUpdateStudent(Student student){
        DataHelper.getInstance().saveOrUpdateStudent(student);
        getAllStudent();
    }
    public void deleteStudent(Student student){
        DataHelper.getInstance().deleteStudent(student);
        getAllStudent();
    }

    public void getAllStudent(){
        studentList = DataHelper.getInstance().getAllStudents();
    }

    public List<Student> getStudentList() {
        return studentList;
    }
}

web/pages/professors.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <title>Система хранения и управления данными об учащихся и преподавателях</title>
</h:head>
<h:body>
    <ui:composition template="../templates/template.xhtml">
        <ui:define name="content">
            <h:dataTable value="#{professorController.professorList}" var="prof"
                         styleClass="table"
                         border="1"
                         headerClass="tableHeader"
                         rowClasses="tableOddRow,tableEvenRow">
                <h:column>
                    <f:facet name="header">Фамилия</f:facet>
                    <h:outputLabel value="#{prof.surname}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Имя</f:facet>
                    <h:outputLabel value="#{prof.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Отчество</f:facet>
                    <h:outputLabel value="#{prof.middleName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Перечень предметов</f:facet>
                    <h:outputLabel value="#{prof.allSubjectsAsString}"/>
                </h:column>
            </h:dataTable>
            <p>Найдено преподователей: #{professorController.professorList.size()}</p>
        </ui:define>
    </ui:composition>
</h:body>
</html>

web/pages/students.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Система хранения и управления данными об учащихся и преподавателях</title>
    <h:outputStylesheet library="css" name="table.css"/>
</h:head>
<h:body>

    <ui:composition template="../templates/template.xhtml">
        <ui:define name="content">
            <h:form id="mainForm">
                <p:dataTable var="st" value="#{studentTableView.students}"
                             id="studentTable"
                             widgetVar="studentTable"
                             resizableColumns="true"
                             editable="true"
                             filteredValue="#{studentTableView.filteredStudents}"
                             rowKey="#{st.studentId}"
                             emptyMessage="Записи не найдены"
                             selection="#{studentTableView.selectedStudent}"
                             selectionMode="single">

                    <p:column headerText="Фамилия" filterBy="#{st.surname}" filterMatchMode="contains">
                        <h:outputText value="#{st.surname}" />
                    </p:column>

                    <p:column headerText="Имя" filterBy="#{st.name}" filterMatchMode="contains">
                        <h:outputText value="#{st.name}" />
                    </p:column>

                    <p:column headerText="Отчество" filterBy="#{st.middlename}" filterMatchMode="contains">
                        <h:outputText value="#{st.middlename}" />
                    </p:column>

                    <p:column headerText="Номер группы" filterBy="#{st.studentGroup.shortDescription}" filterMatchMode="contains">
                        <h:outputText value="#{st.studentGroup.shortDescription}" />
                    </p:column>

                    <p:column headerText="Специальность" filterBy="#{st.studentGroup.specialty}" filterMatchMode="contains">
                        <h:outputText value="#{st.studentGroup.specialty}" />
                    </p:column>

                    <p:column headerText="Факультет" filterBy="#{st.studentGroup.faculty.name}" filterMatchMode="contains">
                        <h:outputText value="#{st.studentGroup.faculty.name}" />
                    </p:column>

                    <f:facet name="footer">
                        <p:commandButton process="studentTable" action="#{studentTableView.addStudent()}" update=":mainForm:studentEdit" icon="ui-icon-plusthick" value="Добавить" oncomplete="PF('studentDialog').show()"/>
                        <p:commandButton process="studentTable" action="#{studentTableView.editStudent()}" update=":mainForm:studentEdit" icon="ui-icon-pencil" value="Редактировать" oncomplete="PF('studentDialog').show()" />
                        <p:commandButton process="studentTable" action="#{studentTableView.deleteStudent()}" update=":mainForm" icon="ui-icon-trash" value="Удалить" />
                    </f:facet>

                </p:dataTable>

                <p:dialog header="Редактирование" widgetVar="studentDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                    <p:outputPanel id="studentEdit" style="text-align:center;">
                        <h:panelGroup rendered="#{not empty studentTableView.selectedStudent}">
                            <h:form>
                                <p:panelGrid  columns="2" rendered="#{not empty studentTableView.selectedStudent}" columnClasses="label,value">
                                    <h:outputText value="Фамилия:" />
                                    <p:outputPanel>
                                        <h:inputText id="surname-input" value="#{studentTableView.selectedStudent.surname}" required="true" requiredMessage="Введите фамилию"/>
                                        <p:message for="surname-input"/>
                                    </p:outputPanel>


                                    <h:outputText value="Имя:" />
                                    <p:outputPanel>
                                        <h:inputText id="name-input" value="#{studentTableView.selectedStudent.name}" required="true" requiredMessage="Введите имя"/>
                                        <p:message for="name-input"/>
                                    </p:outputPanel>

                                    <h:outputText value="Отчество:" />
                                    <h:inputText id="midname-input" value="#{studentTableView.selectedStudent.middlename}" />

                                    <h:outputText value="Факультет"/>
                                    <p:selectOneMenu id="selectFaculty" value="#{studentTableView.selectedFaculty}" effect="fold"
                                            converter="facultyConverter">
                                        <p:ajax update="selectGroup" />
                                        <f:selectItems value="#{studentTableView.allFaculties}" var="f" itemLabel="#{f.name}" itemValue="#{f}"/>
                                    </p:selectOneMenu>

                                    <h:outputText value="группа"/>
                                    <p:selectOneMenu id="selectGroup" value="#{studentTableView.selectedStudent.studentGroup}" effect="fold" required="true" converter="groupConverter">
                                        <f:selectItems value="#{studentTableView.selectedFaculty.groupsList}" var="g" itemValue="#{g}" />
                                    </p:selectOneMenu>

                                </p:panelGrid>
                                <p:commandButton process="@form" update=":mainForm:studentEdit" actionListener="#{studentTableView.saveOrUpdate}" icon="ui-icon-check" value="Применить" action="students"/>
                                <p:commandButton immediate="true" process="@all" update=":mainForm" icon="ui-icon-closethick" value="Отмена" oncomplete="PF(PF('studentDialog').hide())"/>
                            </h:form>
                        </h:panelGroup>
                        <h:outputText value="Выберите студента для редактирования" rendered="#{empty studentTableView.selectedStudent}"/>

                    </p:outputPanel>
                </p:dialog>

            </h:form>
        </ui:define>
    </ui:composition>

</h:body>
</html>